import Head from 'next/head';
import React, { useEffect, useState } from 'react'
import Card from '../../components/Card/Card'
import DefaultLayout from '../../layouts/Default';

export default function index() {

    const [cats, setCats] = useState([]);

    const fetchCats = async () => {
        const response = await fetch('api/cats');
        const data = await response.json();
        setCats(data);
    } 
    
    useEffect(() => {
        fetchCats();
    },[])

    return (
        <>
        <Head>
            <title>Our Cats</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <DefaultLayout>
            <div className="container mt-5">
                <div style={{ display:"flex", flexWrap:"wrap", justifyContent:"space-between" }}>
                {cats.map(item => (
                    <Card key={item.id}
                        name={item.name}
                        phone={item.phone} 
                        email={item.email} 
                        image={item.image} 
                        id={item.id}
                    />
                ))}  
                </div>
            </div>
        </DefaultLayout>
        </>
    )
}
